Repository ReflectiveEarth/reflective-potential, pull requests merged in 2021-08, with the labels that each got.

#9 Merge feature/github-discussion-docs into main
  CHANGELOG.md
  SUPPORT.md
Labels: documentation

#11 Merge feature/project-templates into main
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: documentation, enhancement

#13 Merge bugfix/issue-templates into main
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  CHANGELOG.md
Labels: bug

#14 Update README.md to account for env and environment folder in shell commands
  README.md
Labels: documentation
